# Site settings
title: Electricians of Dallas, LLC
email: emilysharpton@electriciansofdallas.net
url: 
description: "Electricians of Dallas is a family owned company that provides reliable services for both residential and commercial projects."
keywords: "electrician, technician, Dallas, Carrollton, panel"
skills: "<p><strong>Electricians of  Dallas</strong> is a family owned and operated electrical contracting company</i> servicing both residential and commercial customers <strong>since 2003.</strong></p>"
meta_author: Peña Victor
baseurl : /eoc_blog_test

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3CB371
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 000 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Electricians of Dallas, LLC
  location:
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: yelp
    url: https://www.yelp.com/biz/electricians-of-dallas-carrollton-3?osq=Electricians+of+Dallas%2C+LLC
  - title: facebook
    url: https://www.facebook.com/people/Electricians-of-Dallas-LLC/100077930851213/
  - title: google
    url: https://g.co/kgs/Dga7s8
  - title: youtube
    url:
  - title: nextdoor
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
